// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@tunorth.ac.th"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attempts/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attempts"
                ],
                "summary": "ดูประวัติการสอบของฉัน",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.ExamAttempt"
                            }
                        }
                    }
                }
            }
        },
        "/attempts/start": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attempts"
                ],
                "summary": "เริ่มทำข้อสอบ",
                "parameters": [
                    {
                        "description": "Exam ID",
                        "name": "exam_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "exam_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/attempts/submit": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attempts"
                ],
                "summary": "ส่งคำตอบ",
                "parameters": [
                    {
                        "description": "คำตอบ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                " answers": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_ports.SubmitAnswerRequest"
                                    }
                                },
                                "attempt_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "ตรวจสอบ username/password และรับ JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "เข้าสู่ระบบ",
                "parameters": [
                    {
                        "description": "ข้อมูลล็อคอิน",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_handler.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "ลงทะเบียนผู้ใช้งานเข้าสู่ระบบ (Student, Teacher)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "สมัครสมาชิกใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลสมัครสมาชิก",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_handler.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/exams": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "ดูรายการชุดข้อสอบทั้งหมด",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Exam"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "สร้างชุดข้อสอบ",
                "parameters": [
                    {
                        "description": "ข้อมูลชุดข้อสอบ",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_handler.CreateExamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Exam"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/exams/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exams"
                ],
                "summary": "ดูรายละเอียดชุดข้อสอบ (รวมถึงตัวโจทย์)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Exam ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Exam"
                        }
                    }
                }
            }
        },
        "/questions": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "สร้างโจทย์พร้อมตัวเลือก",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "สร้างข้อสอบใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลโจทย์และตัวเลือก",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_handler.CreateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Question"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/questions/subject/{subjectId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "ดึงข้อสอบตามวิชา",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subject ID",
                        "name": "subjectId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Question"
                            }
                        }
                    }
                }
            }
        },
        "/questions/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "ลบข้อสอบ",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Question ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/subjects": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subjects"
                ],
                "summary": "ดึงรายวิชาทั้งหมด",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Subject"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "เพิ่มรายวิชาเข้าสู่ระบบ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subjects"
                ],
                "summary": "สร้างรายวิชาใหม่",
                "parameters": [
                    {
                        "description": "ข้อมูลวิชา",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_handler.CreateSubjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Subject"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/subjects/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subjects"
                ],
                "summary": "ดึงรายละเอียดวิชาตาม ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subject ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Subject"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subjects"
                ],
                "summary": "แก้ไขรายวิชา",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subject ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ข้อมูลที่ต้องการแก้ไข",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapters_handler.CreateSubjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Subjects"
                ],
                "summary": "ลบรายวิชา",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Subject ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_nogittis_tunorth-oes-backend_internal_core_domain.Choice": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "is_correct": {
                    "description": "เป็นคำตอบที่ถูกหรือไม่",
                    "type": "boolean"
                },
                "question_id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_nogittis_tunorth-oes-backend_internal_core_domain.Exam": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "type": "string"
                },
                "duration": {
                    "description": "เวลาทำข้อสอบ (นาที)",
                    "type": "integer",
                    "example": 60
                },
                "end_time": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00Z"
                },
                "id": {
                    "type": "integer"
                },
                "questions": {
                    "description": "Relation: ชุดนี้มีข้อสอบอะไรบ้าง",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Question"
                    }
                },
                "start_time": {
                    "type": "string",
                    "example": "2026-03-01T09:00:00Z"
                },
                "subject_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "example": "สอบกลางภาค 2/2568"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_nogittis_tunorth-oes-backend_internal_core_domain.ExamAnswer": {
            "type": "object",
            "properties": {
                "attemptID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "questionID": {
                    "type": "integer"
                },
                "selectedChoiceID": {
                    "description": "choice ที่นักเรียนเลือก",
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_nogittis_tunorth-oes-backend_internal_core_domain.ExamAttempt": {
            "type": "object",
            "properties": {
                "answers": {
                    "description": "Relation: ตอบข้อไหนไปบ้าง",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.ExamAnswer"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "end_time": {
                    "description": "เวลาที่กดส่งข้อสอบ",
                    "type": "string"
                },
                "exam": {
                    "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Exam"
                },
                "exam_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_submitted": {
                    "type": "boolean"
                },
                "max_score": {
                    "description": "คะแนนเต็ม (จำนวนข้อ)",
                    "type": "integer"
                },
                "score": {
                    "description": "คะแนนรวมที่ได้",
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_nogittis_tunorth-oes-backend_internal_core_domain.Question": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.Choice"
                    }
                },
                "content": {
                    "description": "เนื้อหาโจทย์",
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "difficulty": {
                    "description": "1=ง่าย, 2=กลาง, 3=ยาก",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "subject_id": {
                    "description": "ผูกกับวิชาไหน",
                    "type": "integer"
                },
                "type": {
                    "$ref": "#/definitions/github_com_nogittis_tunorth-oes-backend_internal_core_domain.QuestionType"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_nogittis_tunorth-oes-backend_internal_core_domain.QuestionType": {
            "type": "string",
            "enum": [
                "MCQ"
            ],
            "x-enum-comments": {
                "MCQ": "ปรนัย (เลือกตอบ)"
            },
            "x-enum-descriptions": [
                "ปรนัย (เลือกตอบ)"
            ],
            "x-enum-varnames": [
                "MCQ"
            ]
        },
        "github_com_nogittis_tunorth-oes-backend_internal_core_domain.Subject": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "รหัสวิชา (ห้ามซ้ำ)",
                    "type": "string",
                    "example": "MAT101"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "description": {
                    "description": "คำอธิบาย",
                    "type": "string",
                    "example": "วิชาคณิตศาสตร์พื้นฐาน"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "description": "เปิดใช้งานหรือไม่",
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "description": "ชื่อวิชา",
                    "type": "string",
                    "example": "Mathematics"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "github_com_nogittis_tunorth-oes-backend_internal_core_ports.SubmitAnswerRequest": {
            "type": "object",
            "properties": {
                "choice_id": {
                    "type": "integer"
                },
                "question_id": {
                    "type": "integer"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "internal_adapters_handler.ChoiceRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "is_correct": {
                    "type": "boolean"
                }
            }
        },
        "internal_adapters_handler.CreateExamRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "duration": {
                    "description": "นาที",
                    "type": "integer"
                },
                "end_time": {
                    "type": "string",
                    "example": "2026-03-01T12:00:00+07:00"
                },
                "question_ids": {
                    "description": "รายการ ID ข้อสอบที่จะเอามาใส่",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "start_time": {
                    "description": "รับเป็น String ISO8601",
                    "type": "string",
                    "example": "2026-03-01T09:00:00+07:00"
                },
                "subject_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_adapters_handler.CreateQuestionRequest": {
            "type": "object",
            "properties": {
                "choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_adapters_handler.ChoiceRequest"
                    }
                },
                "content": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "subject_id": {
                    "type": "integer"
                }
            }
        },
        "internal_adapters_handler.CreateSubjectRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "MAT101"
                },
                "description": {
                    "type": "string",
                    "example": "Basic Math"
                },
                "name": {
                    "type": "string",
                    "example": "Mathematics"
                }
            }
        },
        "internal_adapters_handler.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "pass1234"
                },
                "username": {
                    "type": "string",
                    "example": "student01"
                }
            }
        },
        "internal_adapters_handler.RegisterRequest": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "Somsak"
                },
                "last_name": {
                    "type": "string",
                    "example": "Rakrian"
                },
                "password": {
                    "type": "string",
                    "example": "pass1234"
                },
                "role": {
                    "description": "admin, teacher, student",
                    "type": "string",
                    "example": "student"
                },
                "username": {
                    "type": "string",
                    "example": "student01"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8880",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "TUNorth-OES API",
	Description:      "API สำหรับระบบจัดสอบออนไลน์ โรงเรียนเตรียมอุดมศึกษา ภาคเหนือ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
